# MoveIt2 uses this file to connect to ros2_control controllers

# Define the controller manager namespace
controller_manager_ns: controller_manager

# Specify which controllers MoveIt2 should use
moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller
  
  arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - shoulder_pitch_joint
      - shoulder_roll_joint
      - upperarm_joint
      - elbow_joint
      - wrist_joint